# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K_Nn9pDwVSYtyRJttb-EnWwKZF7CvwSG
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder

df=pd.DataFrame({
    'color':['red','blue','green','green','red','blue'],
    'size':['small','medium','large','medium','small','large'],
    'gender':['male','female','male','female','male','female'],
})

df.head()

encoder=OneHotEncoder()

encoder.fit_transform(df[["color"]])

encoded_color=encoder.fit_transform(df[["color"]]).toarray()
encoded_color

encoded_size=encoder.fit_transform(df[["size"]]).toarray()
print(encoded_size)

df=pd.DataFrame(encoded_color,columns=encoder.get_feature_names_out())
print(df)

